name       : akonadiconsole
version    : 21.12.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/akonadiconsole-21.12.1.tar.xz : 3f5169cb2d572d9e6f8b6bd9bbf6302769da39a9e0db934596a0af2b17655cb4
license    :
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Akonadi management and debugging console
description: |
    Akonadi management and debugging console
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - calendarsupport-devel
    - grantleetheme-devel
    - kcalendarcore-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - libkdepim-devel
    - libkleo-devel
    - messagelib-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
