name       : akonadiconsole
version    : 21.08.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/akonadiconsole-21.08.1.tar.xz : d3f9ffbab8193b9838a36d7381cf3275849944b710d3bf04d297bef1cdbaf4b6
license    :
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Akonadi management and debugging console
description: |
    Akonadi management and debugging console
builddeps  :
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - calendarsupport-devel
    - grantleetheme-devel
    - kcalendarcore-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - libkdepim-devel
    - libkleo-devel
    - messagelib-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
