name       : akonadiconsole
version    : 23.04.3
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/akonadiconsole-23.04.3.tar.xz : 938e1c582e5cea6f69bc869a06f010781cb295e76a9bf7c4fa67c4d7f3c0bc00
license    :
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Akonadi management and debugging console
description: |
    Akonadi management and debugging console
builddeps  :
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(xapian-core)
    - akonadi-devel
    - akonadi-calendar-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - calendarsupport-devel
    - grantleetheme-devel
    - kcalendarcore-devel
    - kcompletion-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextaddons-devel
    - ktextwidgets-devel
    - libkdepim-devel
    - libkleo-devel
    - messagelib-devel
    - pimcommon-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
